package modelo.entidad;
// Generated 04-25-2021 08:56:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idpais;
     private String nombre;
     private Set<Remesa> remesas = new HashSet<Remesa>(0);

    public Pais() {
    }

    public Pais(String nombre, Set<Remesa> remesas) {
       this.nombre = nombre;
       this.remesas = remesas;
    }
   
    public Integer getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(Integer idpais) {
        this.idpais = idpais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Remesa> getRemesas() {
        return this.remesas;
    }
    
    public void setRemesas(Set<Remesa> remesas) {
        this.remesas = remesas;
    }




}


