package modelo.entidad;
// Generated 04-25-2021 08:56:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Remesa generated by hbm2java
 */
public class Remesa  implements java.io.Serializable {


     private Integer idremesa;
     private Cliente cliente;
     private Estado estado;
     private Pais pais;
     private Usuario usuario;
     private Double monto;
     private Double comision;
     private Double total;
     private String destinatario;
     private String claveRemesa;
     private Date fechaGrabacion;
     private Date fechaRecepcion;
     private Date fechaExpiracion;

    public Remesa() {
    }

	
    public Remesa(Cliente cliente, Estado estado, Pais pais, Usuario usuario) {
        this.cliente = cliente;
        this.estado = estado;
        this.pais = pais;
        this.usuario = usuario;
    }
    public Remesa(Cliente cliente, Estado estado, Pais pais, Usuario usuario, Double monto, Double comision, Double total, String destinatario, String claveRemesa, Date fechaGrabacion, Date fechaRecepcion, Date fechaExpiracion) {
       this.cliente = cliente;
       this.estado = estado;
       this.pais = pais;
       this.usuario = usuario;
       this.monto = monto;
       this.comision = comision;
       this.total = total;
       this.destinatario = destinatario;
       this.claveRemesa = claveRemesa;
       this.fechaGrabacion = fechaGrabacion;
       this.fechaRecepcion = fechaRecepcion;
       this.fechaExpiracion = fechaExpiracion;
    }
   
    public Integer getIdremesa() {
        return this.idremesa;
    }
    
    public void setIdremesa(Integer idremesa) {
        this.idremesa = idremesa;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Double getComision() {
        return this.comision;
    }
    
    public void setComision(Double comision) {
        this.comision = comision;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getDestinatario() {
        return this.destinatario;
    }
    
    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }
    public String getClaveRemesa() {
        return this.claveRemesa;
    }
    
    public void setClaveRemesa(String claveRemesa) {
        this.claveRemesa = claveRemesa;
    }
    public Date getFechaGrabacion() {
        return this.fechaGrabacion;
    }
    
    public void setFechaGrabacion(Date fechaGrabacion) {
        this.fechaGrabacion = fechaGrabacion;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }




}


