package modelo.entidad;
// Generated 04-25-2021 08:56:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private String usuario;
     private String clave;
     private String nombreCompleto;
     private Date fechaCreacion;
     private Boolean activo;
     private Set<Remesa> remesas = new HashSet<Remesa>(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String clave) {
        this.usuario = usuario;
        this.clave = clave;
    }
    public Usuario(String usuario, String clave, String nombreCompleto, Date fechaCreacion, Boolean activo, Set<Remesa> remesas) {
       this.usuario = usuario;
       this.clave = clave;
       this.nombreCompleto = nombreCompleto;
       this.fechaCreacion = fechaCreacion;
       this.activo = activo;
       this.remesas = remesas;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set<Remesa> getRemesas() {
        return this.remesas;
    }
    
    public void setRemesas(Set<Remesa> remesas) {
        this.remesas = remesas;
    }




}


